name: Micronaut CI/CD

on:
  pull_request:
    types: [closed]

jobs:
  check-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged
        id: check_merge
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "PR was merged!"
            echo "run_ci=true" >> $GITHUB_ENV
          else
            echo "PR was closed without merging. Skipping CI."
            echo "run_ci=false" >> $GITHUB_ENV
          fi

  build:
    needs: check-merge
    if: needs.check-merge.outputs.merged == 'true'
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mn_playground
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost -u root --password=password"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '21'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Ensure MySQL Database Exists
        run: |
          mysql -h 127.0.0.1 -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS mn_playground;"

      - name: Build and Test Application
        run: ./gradlew build
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: password
          DB_NAME: mn_playground

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-app
          path: build/libs/*.jar